Repository Chrezm/DRO-Client, pull requests merged in 2021-04, with the labels that each got.

#138 Solves #137, stop all sound effects on a new message
  include/aosfxplayer.h
  src/aosfxplayer.cpp
  src/courtroom.cpp
Labels: fix

#140 Fix config not reading saved display empty messages option
  src/aoconfig.cpp
Labels: bug

#132 Mac Support
  .gitignore
  dronline-client.pro
  icon.icns
  include/drpather.h
  include/hardware_functions.h
  res/ui/config_panel.ui
  src/aoconfig.cpp
  src/aoconfigpanel.cpp
  src/aonotepicker.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/draudiostreamfamily.cpp
  src/drpather.cpp
  src/hardware_functions.cpp
  src/lobby.cpp
  src/main.cpp
  src/path_functions.cpp
Labels: enhancement

#145 Self-identification highlight coloring
  include/aoconfig.h
  include/aoconfigpanel.h
  include/courtroom.h
  include/datatypes.h
  res/ui/config_panel.ui
  src/aoconfig.cpp
  src/aoconfigpanel.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
Labels: enhancement
