Repository Chrezm/DRO-Client, pull requests merged in 2021-05, with the labels that each got.

#143 Basic showname QOL support
  include/aoapplication.h
  include/aoconfig.h
  include/aoconfigpanel.h
  include/courtroom.h
  res/ui/config_panel.ui
  src/aoapplication.cpp
  src/aoconfig.cpp
  src/aoconfigpanel.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/emotes.cpp
  src/packet_distribution.cpp
Labels: enhancement

#156 Added character sound pathing to SfxPlayer
  include/aosfxplayer.h
  src/aoevidencedisplay.cpp
  src/aosfxplayer.cpp
  src/courtroom.cpp
  src/file_functions.cpp
Labels: enhancement

#158 Fix invalid slot names
  src/courtroom_widgets.cpp
Labels: bug

#159 Added include option for char.ini
  include/aoapplication.h
  include/aocharmovie.h
  include/aoemotebutton.h
  include/aosfxplayer.h
  include/aoshoutplayer.h
  include/courtroom.h
  include/datatypes.h
  src/aocharmovie.cpp
  src/aoemotebutton.cpp
  src/aosfxplayer.cpp
  src/aoshoutplayer.cpp
  src/courtroom.cpp
  src/emotes.cpp
  src/packet_distribution.cpp
  src/path_functions.cpp
  src/text_file_functions.cpp
Labels: enhancement

#157 Improve path lookup
  src/path_functions.cpp
Labels: enhancement

#163 Make reloading themes not reset text cursor or emote
  include/courtroom.h
  src/courtroom.cpp
  src/emotes.cpp
Labels: bug

#167 Maintenance - 2021, May
  dronline-client.pro
  include/aoapplication.h
  include/aoblipplayer.h
  include/aoevidencedisplay.h
  include/aoimagedisplay.h
  include/aopacket.h
  include/courtroom.h
  include/datatypes.h
  include/drpather.h
  include/file_functions.h
  include/lobby.h
  include/networkmanager.h
  include/version.h
  src/aoapplication.cpp
  src/aoblipplayer.cpp
  src/aoconfig.cpp
  src/aoevidencedisplay.cpp
  src/aoimagedisplay.cpp
  src/aopacket.cpp
  src/charselect.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/debug_functions.cpp
  src/draudioengine_p.cpp
  src/draudiostreamfamily.cpp
  src/drpather.cpp
  src/file_functions.cpp
  src/lobby.cpp
  src/main.cpp
  src/networkmanager.cpp
  src/packet_distribution.cpp
  src/path_functions.cpp
  src/text_file_functions.cpp
  src/version.cpp
Labels: optimization

#168 #161 - Ini-swap dropdown
  include/aoconfig.h
  include/courtroom.h
  src/aoapplication.cpp
  src/aoconfig.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/emotes.cpp
  src/packet_distribution.cpp
Labels: enhancement, streamline

#176 Tick rate & speed keywords
  include/aoapplication.h
  include/courtroom.h
  res/ui/config_panel.ui
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/packet_distribution.cpp
Labels: enhancement

#180 Text alignment on fields
  dronline-client.pro
  include/courtroom.h
  include/drtextedit.h
  include/lobby.h
  include/theme.h
  src/charselect.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/emotes.cpp
  src/evidence.cpp
  src/lobby.cpp
  src/theme.cpp
Labels: enhancement

#183 Development into Master
  include/courtroom.h
  src/aoconfig.cpp
  src/charselect.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/emotes.cpp
Labels: enhancement
