Repository Chrezm/DRO-Client, pull requests merged in 2021-06, with the labels that each got.

#188 Font loading
  include/aoapplication.h
  src/aoapplication.cpp
  src/main.cpp
Labels: enhancement

#185 Tick Rate Optimization
  include/courtroom.h
  src/courtroom.cpp
  src/courtroom_widgets.cpp
Labels: optimization

#191 Add missing libraries for Windows action
  .github/workflows/build-all.yml
Labels: bug

#194 Ini-swap charselect tweaks
  include/aocharbutton.h
  include/courtroom.h
  src/aoapplication.cpp
  src/aocharbutton.cpp
  src/charselect.cpp
  src/courtroom.cpp
  src/courtroom_character.cpp
  src/courtroom_widgets.cpp
Labels: enhancement

#195 Improved IC chatlog performance
  include/aoapplication.h
  include/courtroom.h
  res/ui/config_panel.ui
  src/aoapplication.cpp
  src/aoconfig.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/text_file_functions.cpp
  src/theme.cpp
Labels: optimization

#196 Various 2 Electric Boogaloo
  include/aobutton.h
  include/courtroom.h
  src/aobutton.cpp
  src/aocharmovie.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
Labels: bug

#198 Added emote preview, emote and iniswap visibility changes
  include/aoemotebutton.h
  include/courtroom.h
  src/aoemotebutton.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/emotes.cpp
Labels: enhancement
