Repository Chrezm/DRO-Client, pull requests merged in 2021-02, with the labels that each got.

#114 Resolves #113 - Replaced audio engine & added some enhancements
  dronline-client.pro
  include/aoabstractplayer.h
  include/aoblipplayer.h
  include/aoconfig.h
  include/aoconfigpanel.h
  include/aomusicplayer.h
  include/aoobject.h
  include/aosfxplayer.h
  include/aoshoutplayer.h
  include/aosystemplayer.h
  include/courtroom.h
  include/draudio.h
  include/draudioengine.h
  include/draudioerror.h
  include/draudiostream.h
  include/draudiostreamfamily.h
  res/ui/config_panel.ui
  src/aoabstractplayer.cpp
  src/aoblipplayer.cpp
  src/aoconfig.cpp
  src/aoconfigpanel.cpp
  src/aoevidencedisplay.cpp
  src/aomusicplayer.cpp
  src/aoobject.cpp
  src/aosfxplayer.cpp
  src/aoshoutplayer.cpp
  src/aosystemplayer.cpp
  src/audio_functions.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/draudio.cpp
  src/draudioengine.cpp
  src/draudioerror.cpp
  src/draudiostream.cpp
  src/draudiostreamfamily.cpp
  src/text_file_functions.cpp
Labels: enhancement

#118 Cleanup
  dronline-client.pro
  include/aoblipplayer.h
  include/aomusicplayer.h
  include/datatypes.h
  include/draudioengine.h
  include/draudiostream.h
  include/draudiostreamfamily.h
  src/aoblipplayer.cpp
  src/datatypes.cpp
  src/discord_rich_presence.cpp
  src/draudioengine.cpp
  src/draudiostream.cpp
  src/draudiostreamfamily.cpp
Labels: cleanup

#117 Customize shade of chat message text colors in theme
  include/aoapplication.h
  include/datatypes.h
  src/courtroom.cpp
  src/datatypes.cpp
  src/draudioengine.cpp
  src/text_file_functions.cpp
Labels: enhancement

#120 Resolves #119, added audio-device system
  dronline-client.pro
  include/aoconfig.h
  include/aoconfigpanel.h
  include/datatypes.h
  include/draudio.h
  include/draudiodevice.h
  include/draudioengine.h
  include/draudioengine_p.h
  include/draudioerror.h
  include/draudiostream.h
  include/draudiostreamfamily.h
  res/ui/config_panel.ui
  src/aoconfig.cpp
  src/aoconfigpanel.cpp
  src/draudio.cpp
  src/draudiodevice.cpp
  src/draudioengine.cpp
  src/draudioengine_p.cpp
  src/draudioerror.cpp
  src/draudiostream.cpp
  src/draudiostreamfamily.cpp
  src/main.cpp
Labels: feature

#121 Fixed pathing issues, compiler warnings, ...
  include/aoapplication.h
  include/datatypes.h
  src/aoapplication.cpp
  src/aoemotebutton.cpp
  src/aonotearea.cpp
  src/courtroom.cpp
  src/datatypes.cpp
  src/hardware_functions.cpp
  src/networkmanager.cpp
  src/text_file_functions.cpp
Labels: bug
