Repository Chrezm/DRO-Client, pull requests merged in 2021-03, with the labels that each got.

#129 Better Discord Rich Presence
  dronline-client.pro
  icon-2x.png
  include/aoapplication.h
  include/aoconfig.h
  include/aoconfigpanel.h
  include/discord_rich_presence.h
  include/drdiscord.h
  res/ui/config_panel.ui
  src/aoapplication.cpp
  src/aoconfig.cpp
  src/aoconfigpanel.cpp
  src/courtroom.cpp
  src/discord_rich_presence.cpp
  src/drdiscord.cpp
  src/packet_distribution.cpp
Labels: enhancement

#130 Text alignment
  dronline-client.pro
  include/aonotepad.h
  include/aotimer.h
  include/courtroom.h
  include/datatypes.h
  include/drtextedit.h
  include/lobby.h
  src/aonotepad.cpp
  src/aotimer.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/drtextedit.cpp
  src/lobby.cpp
Labels: enhancement

#127 Closes #125 and #126
  include/aoconfig.h
  include/aoconfigpanel.h
  include/courtroom.h
  include/datatypes.h
  res/ui/config_panel.ui
  src/aoapplication.cpp
  src/aoconfig.cpp
  src/aoconfigpanel.cpp
  src/aotextarea.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/text_file_functions.cpp
Labels: feature

#131 Fixed short audio issues and tweaks to disconnection popup
  include/courtroom.h
  include/draudiostreamfamily.h
  src/aoapplication.cpp
  src/audio_functions.cpp
  src/courtroom.cpp
  src/draudiostream.cpp
  src/draudiostreamfamily.cpp
Labels: bug
