Repository Chrezm/DRO-Client, pull requests merged in 2021-07, with the labels that each got.

#199 Fixed chatlog having issues with URLs and HTML in general
  dronline-client.pro
  include/aotextarea.h
  include/courtroom.h
  include/drchatlog.h
  include/lobby.h
  src/aotextarea.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/drchatlog.cpp
  src/lobby.cpp
Labels: bug

#203 Removed emote filter
  src/text_file_functions.cpp
Labels: bugfix

#202 Reworked frame handling for AOMovie to be more accurate
  include/aomovie.h
  src/aomovie.cpp
Labels: bugfix

#205 Stylesheets improvements
  include/commondefs.h
  include/courtroom.h
  include/theme.h
  src/aonotearea.cpp
  src/commondefs.cpp
  src/courtroom_widgets.cpp
  src/theme.cpp
Labels: enhancement

#204 Build QtApng plugin instead of downloading
  .github/workflows/build-all.yml
Labels: bugfix

#207 Separate area and music listing
  include/courtroom.h
  src/courtroom.cpp
  src/courtroom_sfx.cpp
  src/courtroom_widgets.cpp
Labels: feature

#208 Added character content url
  include/courtroom.h
  src/courtroom.cpp
  src/courtroom_character.cpp
Labels: feature
