Repository Chrezm/DRO-Client, pull requests merged in 2021-08, with the labels that each got.

#211 Implemented #210, miscellaneous changes
  include/aoapplication.h
  include/aoconfig.h
  include/aoconfigpanel.h
  include/commondefs.h
  include/courtroom.h
  include/datatypes.h
  src/aoapplication.cpp
  src/aoconfig.cpp
  src/aoconfigpanel.cpp
  src/aoscene.cpp
  src/commondefs.cpp
  src/courtroom.cpp
  src/path_functions.cpp
  src/server_socket.cpp
Labels: cleanup, feature

#212 Background improvements
  include/commondefs.h
  include/courtroom.h
  src/commondefs.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
Labels: cleanup, bugfix

#213 Renamed gamemode and time of day in config, ...
  include/aoconfig.h
  include/aoconfigpanel.h
  include/courtroom.h
  res/ui/config_panel.ui
  src/aoapplication.cpp
  src/aoconfig.cpp
  src/aoconfigpanel.cpp
  src/courtroom.cpp
  src/path_functions.cpp
  src/server_socket.cpp
Labels: inconsistent
