Repository Chrezm/DRO-Client, pull requests merged in 2022-03, with the labels that each got.

#270 Added DRAudiotrackMetadata, separated character loading, ...
  dronline-client.pro
  include/aoapplication.h
  include/aoconfig.h
  include/aoconfigpanel.h
  include/aomusicplayer.h
  include/courtroom.h
  include/draudiodevice.h
  include/draudioengine.h
  include/draudioengine_p.h
  include/draudiostream.h
  include/draudiostreamfamily.h
  include/draudiotrackmetadata.h
  include/utils.h
  res/ui/config_panel.ui
  src/aoapplication.cpp
  src/aoconfig.cpp
  src/aoconfigpanel.cpp
  src/aomusicplayer.cpp
  src/courtroom.cpp
  src/courtroom_character.cpp
  src/draudiodevice.cpp
  src/draudioengine.cpp
  src/draudioengine_p.cpp
  src/draudiostream.cpp
  src/draudiostreamfamily.cpp
  src/draudiotrackmetadata.cpp
  src/path_functions.cpp
  src/server_socket.cpp
  src/text_file_functions.cpp
  src/utils.cpp
Labels: feature

#269 Use witness background/desk if positional background/desk unavailable
  include/drmovie.h
  src/courtroom.cpp
  src/drmovie.cpp
Labels: feature

#260 Fix unmaximizing giving wrong size if player launched with theme of different size to current one
  include/courtroom.h
  include/theme.h
  src/aoapplication.cpp
  src/charselect.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/lobby.cpp
  src/theme.cpp
Labels: bug

#267 Added Video playing feature
  .github/workflows/build-all.yml
  dronline-client.pro
  include/aoapplication.h
  include/aoconfig.h
  include/aoconfigpanel.h
  include/aoevidencebutton.h
  include/aoevidencedescription.h
  include/aoevidencedisplay.h
  include/courtroom.h
  include/datatypes.h
  include/draudio.h
  include/drvideoscreen.h
  res/ui/config_panel.ui
  src/aoapplication.cpp
  src/aoconfig.cpp
  src/aoconfigpanel.cpp
  src/aoevidencebutton.cpp
  src/aoevidencedescription.cpp
  src/aoevidencedisplay.cpp
  src/courtroom.cpp
  src/courtroom_widgets.cpp
  src/draudioengine.cpp
  src/draudiostream.cpp
  src/draudiostreamfamily.cpp
  src/drvideoscreen.cpp
  src/evidence.cpp
  src/path_functions.cpp
  src/server_socket.cpp
  src/text_file_functions.cpp
Labels: feature

#274 Reworked logger to be faster and safe
  dronline-client.pro
  include/log.h
  include/logger.h
  src/log.cpp
  src/logger.cpp
  src/main.cpp
  src/master_socket.cpp
Labels: optimization
