Repository Chrezm/DRO-Client, pull requests merged in 2022-04, with the labels that each got.

#279 Several file IO optimizations
  .github/workflows/build-all-merge-master.yml
  README.md
  src/aobutton.cpp
  src/aocharbutton.cpp
  src/aoimagedisplay.cpp
  src/aoimagedisplay.h
  src/charselect.cpp
  src/courtroom.cpp
  src/courtroom.h
  src/courtroom_widgets.cpp
  src/datatypes.h
  src/drcharactermovie.cpp
  src/emotes.cpp
  src/file_functions.cpp
  src/file_functions.h
  src/lobby.cpp
  src/main.cpp
  src/theme.cpp
Labels: optimization

#285 Assume v110 server compatible
  dronline-client.pro
  res/ui/config_panel.ui
  src/aoapplication.cpp
  src/aoapplication.h
  src/aoconfig.cpp
  src/aoconfig.h
  src/aoconfigpanel.cpp
  src/aoconfigpanel.h
  src/courtroom.cpp
  src/debug_functions.cpp
  src/debug_functions.h
  src/lobby.cpp
  src/master_socket.cpp
  src/server_socket.cpp
Labels: enhancement, maintenance

#287 Enforce proper start and end ranges in certain at and mid calls
  src/courtroom.cpp
  src/datatypes.h
  src/server_socket.cpp
Labels: bug

#288 Reworked server advertiser, server info, ...
  .github/workflows/build-all-merge-master.yml
  .github/workflows/build-all.yml
  dronline-client.pro
  res/ui/config_panel.ui
  src/aoapplication.cpp
  src/aoapplication.h
  src/aobutton.cpp
  src/aobutton.h
  src/aoconfig.cpp
  src/aoconfig.h
  src/aoconfigpanel.cpp
  src/aoconfigpanel.h
  src/commondefs.cpp
  src/commondefs.h
  src/courtroom.cpp
  src/datatypes.cpp
  src/datatypes.h
  src/drchatlog.cpp
  src/drchatlog.h
  src/drmasterclient.cpp
  src/drmasterclient.h
  src/drserversocket.cpp
  src/drserversocket.h
  src/lobby.cpp
  src/lobby.h
  src/master_socket.cpp
  src/path_functions.cpp
  src/server_socket.cpp
  src/text_file_functions.cpp
  src/theme.cpp
  src/version.cpp
  src/version.h
Labels: enhancement, feature

#293 Added chat message placeholder instructions
  src/courtroom_widgets.cpp
Labels: feature

#291 Added media tester
  dronline-client.pro
  res.qrc
  res/tests/mp4_media_test.mp4
  src/drmediatester.cpp
  src/drmediatester.h
  src/main.cpp
Labels: feature

#296 Added client Id to MS packet
  res/ui/config_panel.ui
  src/aoapplication.cpp
  src/aoapplication.h
  src/aoconfig.cpp
  src/aoconfig.h
  src/aoconfigpanel.cpp
  src/aoconfigpanel.h
  src/courtroom.cpp
  src/courtroom.h
  src/courtroom_widgets.cpp
  src/datatypes.h
  src/server_socket.cpp
Labels: enhancement

#299 Always hide narrator showname
  src/courtroom.cpp
  src/courtroom.h
Labels: bug

#298 Reworked music behavior
  src/courtroom.cpp
  src/courtroom.h
Labels: feature

#300 Added FA and FM packet
  src/aoapplication.h
  src/courtroom.cpp
  src/server_socket.cpp
Labels: enhancement
